version: '3'

services:
  front:
    build: .
    image: novatics-front
    command: sh run.sh
    ports:
      - 8000:8000
    volumes:
      - .:/code
    environment:
      - REACT_APP_BASE_URL=http://localhost:3000/
      - PORT=8000
