version: '3'

services:
  front:
    build: .
    image: novatics-front
    command: yarn start
    ports:
      - 8000:8000
    volumes:
      - .:/code
    environment:
      - REACT_APP_BASE_URL=http://0.0.0.0:3000/
      - PORT=8000
